export const COUNTRIES = [
  'United States',
  'United Kingdom',
  'Canada',
  'Australia',
  'Germany',
  'France',
  'Italy',
  'Spain',
  'Netherlands',
  'Belgium',
  'Switzerland',
  'Austria',
  'Sweden',
  'Norway',
  'Denmark',
  'Finland',
  'Poland',
  'Portugal',
  'Ireland',
  'Greece',
  'Czech Republic',
  'Hungary',
  'Romania',
  'Bulgaria',
  'Croatia',
  'Slovakia',
  'Slovenia',
  'Estonia',
  'Latvia',
  'Lithuania',
  'Luxembourg',
  'Malta',
  'Cyprus',
  'Japan',
  'South Korea',
  'China',
  'India',
  'Singapore',
  'Malaysia',
  'Thailand',
  'Indonesia',
  'Philippines',
  'Vietnam',
  'Hong Kong',
  'Taiwan',
  'New Zealand',
  'South Africa',
  'Brazil',
  'Mexico',
  'Argentina',
  'Chile',
  'Colombia',
  'Peru',
  'UAE',
  'Saudi Arabia',
  'Israel',
  'Turkey',
  'Russia',
  'Ukraine',
  'Egypt',
  'Nigeria',
  'Kenya',
  'Morocco',
  'Tunisia',
  'Algeria',
  'Ghana',
  'Ethiopia',
  'Tanzania',
  'Uganda',
  'Zimbabwe',
  'Botswana',
  'Namibia',
  'Mozambique',
  'Angola',
  'Zambia',
  'Malawi',
  'Madagascar',
  'Mauritius',
  'Seychelles',
  'Rwanda',
  'Burundi',
  'Senegal',
  'Ivory Coast',
  'Cameroon',
  'Gabon',
  'Congo',
  'DRC',
  'Central African Republic',
  'Chad',
  'Niger',
  'Mali',
  'Burkina Faso',
  'Guinea',
  'Sierra Leone',
  'Liberia',
  'Togo',
  'Benin',
  'Gambia',
  'Guinea-Bissau',
  'Cape Verde',
  'São Tomé and Príncipe',
  'Equatorial Guinea',
  'Djibouti',
  'Eritrea',
  'Somalia',
  'Sudan',
  'South Sudan',
  'Libya',
  'Lebanon',
  'Jordan',
  'Syria',
  'Iraq',
  'Iran',
  'Afghanistan',
  'Pakistan',
  'Bangladesh',
  'Sri Lanka',
  'Nepal',
  'Bhutan',
  'Myanmar',
  'Cambodia',
  'Laos',
  'Brunei',
  'East Timor',
  'Papua New Guinea',
  'Fiji',
  'Samoa',
  'Tonga',
  'Vanuatu',
  'Solomon Islands',
  'Palau',
  'Micronesia',
  'Marshall Islands',
  'Kiribati',
  'Tuvalu',
  'Nauru',
  'Cook Islands',
  'Niue',
  'Tokelau',
  'Pitcairn Islands',
  'Norfolk Island',
  'Christmas Island',
  'Cocos Islands',
  'Heard Island',
  'Macquarie Island',
  'French Polynesia',
  'New Caledonia',
  'Wallis and Futuna',
  'American Samoa',
  'Guam',
  'Northern Mariana Islands',
  'Puerto Rico',
  'US Virgin Islands',
  'British Virgin Islands',
  'Anguilla',
  'Montserrat',
  'Turks and Caicos',
  'Cayman Islands',
  'Bermuda',
  'Bahamas',
  'Jamaica',
  'Haiti',
  'Dominican Republic',
  'Cuba',
  'Trinidad and Tobago',
  'Barbados',
  'Saint Lucia',
  'Saint Vincent',
  'Grenada',
  'Antigua and Barbuda',
  'Saint Kitts and Nevis',
  'Dominica',
  'Belize',
  'Costa Rica',
  'Panama',
  'Nicaragua',
  'Honduras',
  'El Salvador',
  'Guatemala',
  'Venezuela',
  'Guyana',
  'Suriname',
  'French Guiana',
  'Ecuador',
  'Bolivia',
  'Paraguay',
  'Uruguay',
  'Falkland Islands',
  'South Georgia',
  'Antarctica',
  'Greenland',
  'Iceland',
  'Faroe Islands',
  'Svalbard',
  'Jan Mayen',
  'Åland Islands',
  'Isle of Man',
  'Jersey',
  'Guernsey',
  'Gibraltar',
  'Andorra',
  'Monaco',
  'San Marino',
  'Vatican City',
  'Liechtenstein',
  'Moldova',
  'Belarus',
  'Kazakhstan',
  'Uzbekistan',
  'Turkmenistan',
  'Tajikistan',
  'Kyrgyzstan',
  'Mongolia',
  'North Korea',
  'Yemen',
  'Oman',
  'Qatar',
  'Bahrain',
  'Kuwait',
  'Azerbaijan',
  'Armenia',
  'Georgia',
  'Kosovo',
  'Montenegro',
  'Serbia',
  'Bosnia and Herzegovina',
  'North Macedonia',
  'Albania',
];

// Remove duplicates and sort
export const UNIQUE_COUNTRIES = Array.from(new Set(COUNTRIES)).sort();

